/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Login
         * @description Create the user if absent and hand back a token.
         *
         *     Also creates a default watchlist, because a user with no watchlist has no
         *     digest, and a first-run experience of "nothing here" is indistinguishable
         *     from the product being broken.
         */
        post: operations["dev_login_api_auth_dev_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_api_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_api_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_watchlists__watchlist_id__get"];
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_watchlists__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_watchlists__watchlist_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlists/{watchlist_id}/items/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_watchlists__watchlist_id__items__symbol__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_watchlists__watchlist_id__items__symbol__patch"];
        trace?: never;
    };
    "/api/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Symbols */
        get: operations["search_symbols_api_symbols_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Symbol */
        get: operations["get_symbol_api_symbols__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Digest */
        get: operations["get_digest_api_digest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Seen
         * @description Advance watermarks for symbols this user actually watches.
         *
         *     Unknown symbols are reported back rather than silently dropped or allowed
         *     to fail the whole batch. Silently dropping leaves a client that believes
         *     it has marked a row read when it has not, and it has no way to find out.
         *     Failing the batch punishes eleven good rows for one bad one.
         */
        post: operations["post_seen_api_seen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_debug_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/inject-fault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inject Fault */
        post: operations["inject_fault_api_debug_inject_fault_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seek */
        post: operations["seek_api_debug_seek_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/scenarios/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Scenario
         * @description Seek the clock and inject the faults for one preset, in one call.
         *
         *     The demo is driven from here, so it has to be a single button press with
         *     nothing to remember under pressure.
         *
         *     Previously scheduled faults are cleared first. Without that, running the
         *     split scenario and then the quiet day leaves the split still firing, and
         *     the "quiet day" that is supposed to show silence shows a corporate action
         *     instead -- which is the one moment in the demo where a stale fault is most
         *     obvious and least recoverable.
         */
        post: operations["run_scenario_api_debug_scenarios__key__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the API is up, and separately whether the poller still is.
         *
         *     last_poll_at is the field that matters. An API answering happily in front
         *     of a dead worker serves prices that have quietly stopped moving, and
         *     nothing else in the system will tell you.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddItemRequest */
        AddItemRequest: {
            /** Symbol */
            symbol: string;
            /** Cost Basis */
            cost_basis?: number | null;
            /** Note */
            note?: string | null;
        };
        /** CreateWatchlistRequest */
        CreateWatchlistRequest: {
            /**
             * Name
             * @default My watchlist
             */
            name: string;
        };
        /** DevLoginRequest */
        DevLoginRequest: {
            /** Email */
            email: string;
        };
        /** DigestOut */
        DigestOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Market State */
            market_state: string;
            market?: components["schemas"]["MarketOut"] | null;
            /** Needs Attention */
            needs_attention?: components["schemas"]["DigestRowOut"][];
            /** Quiet */
            quiet?: components["schemas"]["DigestRowOut"][];
            /**
             * Quiet Summary
             * @default
             */
            quiet_summary: string;
            /** Degraded */
            degraded?: components["schemas"]["DigestRowOut"][];
        };
        /** DigestRowOut */
        DigestRowOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Price */
            price?: number | null;
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Freshness */
            freshness: string;
            /** Change Since Seen */
            change_since_seen?: number | null;
            /** Seen At */
            seen_at?: string | null;
            /** Score */
            score: number;
            /** Primary Reason */
            primary_reason?: string | null;
            /** Events */
            events?: components["schemas"]["EventOut"][];
            /** Data Note */
            data_note?: string | null;
        };
        /** EventOut */
        EventOut: {
            /** Type */
            type: string;
            /** Severity */
            severity: number;
            /** Explanation */
            explanation: string;
            /** Payload */
            payload?: Record<string, never>;
            /** Occurred At */
            occurred_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Market State */
            market_state: string;
            /** Provider */
            provider: string;
            /** Hot Set Size */
            hot_set_size: number;
            /** Last Poll At */
            last_poll_at?: string | null;
            /** Last Poll Symbol Count */
            last_poll_symbol_count: number;
            /** Last Poll Rejected Count */
            last_poll_rejected_count: number;
        };
        /** InjectFaultRequest */
        InjectFaultRequest: {
            /** Kind */
            kind: string;
            /** Symbol */
            symbol?: string | null;
            /**
             * Magnitude
             * @default 1
             */
            magnitude: number;
            /** Duration Minutes */
            duration_minutes?: number | null;
        };
        /** MarketOut */
        MarketOut: {
            /** Index Symbol */
            index_symbol: string;
            /** Index Return */
            index_return: number;
            /** Breadth */
            breadth: number;
            /** Is Market Wide */
            is_market_wide: boolean;
            /** Headline */
            headline: string;
        };
        /** ScenarioFault */
        ScenarioFault: {
            /** Kind */
            kind: string;
            /** Symbol */
            symbol?: string | null;
            /**
             * Magnitude
             * @default 1
             */
            magnitude: number;
            /** Duration Minutes */
            duration_minutes?: number | null;
        };
        /** ScenarioOut */
        ScenarioOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /**
             * Seek To
             * Format: date-time
             */
            seek_to: string;
            /** Faults */
            faults?: components["schemas"]["ScenarioFault"][];
        };
        /** SeekRequest */
        SeekRequest: {
            /**
             * To
             * Format: date-time
             */
            to: string;
        };
        /** SeenEntryIn */
        SeenEntryIn: {
            /** Symbol */
            symbol: string;
            /**
             * Seen At
             * Format: date-time
             */
            seen_at: string;
            /** Price */
            price?: number | null;
        };
        /** SeenRequest */
        SeenRequest: {
            /** Entries */
            entries?: components["schemas"]["SeenEntryIn"][];
        };
        /** SeenResponse */
        SeenResponse: {
            /** Updated */
            updated: number;
            /** Rejected */
            rejected?: string[];
        };
        /** SymbolDetail */
        SymbolDetail: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
            /** Sector */
            sector?: string | null;
            /** Benchmark */
            benchmark: string;
            stats?: components["schemas"]["SymbolStatsOut"] | null;
            /** Recent Events */
            recent_events?: components["schemas"]["EventOut"][];
        };
        /** SymbolOut */
        SymbolOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
        };
        /** SymbolStatsOut */
        SymbolStatsOut: {
            /** Mean Ret 30D */
            mean_ret_30d: number;
            /** Std Ret 30D */
            std_ret_30d: number;
            /** Avg Vol 20D */
            avg_vol_20d: number;
            /** High 52W */
            high_52w: number;
            /** Low 52W */
            low_52w: number;
            /** Beta 60D */
            beta_60d: number;
            /** Sample Size */
            sample_size: number;
            /** Computed At */
            computed_at?: string | null;
            /** Expected Daily Move */
            expected_daily_move: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** User Id */
            user_id: number;
            /** Token */
            token: string;
        };
        /** UpdateItemRequest */
        UpdateItemRequest: {
            /** Cost Basis */
            cost_basis?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistDetail */
        WatchlistDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Items */
            items?: components["schemas"]["WatchlistItemOut"][];
        };
        /** WatchlistItemOut */
        WatchlistItemOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Cost Basis */
            cost_basis?: number | null;
            /** Note */
            note?: string | null;
            /** Price At Add */
            price_at_add?: number | null;
            /** Added At */
            added_at?: string | null;
            /** Price */
            price?: number | null;
            /** As Of */
            as_of?: string | null;
            /** Source */
            source?: string | null;
            /** Freshness */
            freshness?: string | null;
        };
        /** WatchlistSummary */
        WatchlistSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Item Count */
            item_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dev_login_api_auth_dev_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_api_watchlists_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_api_watchlists_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_watchlists__watchlist_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_watchlists__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_watchlists__watchlist_id__items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_watchlists__watchlist_id__items__symbol__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_watchlists__watchlist_id__items__symbol__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                watchlist_id: number;
                symbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_symbols_api_symbols_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_symbol_api_symbols__symbol__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_digest_api_digest_get: {
        parameters: {
            query?: {
                watchlist_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_seen_api_seen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_stream_get: {
        parameters: {
            query?: {
                symbols?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_debug_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioOut"][];
                };
            };
        };
    };
    inject_fault_api_debug_inject_fault_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectFaultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seek_api_debug_seek_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scenario_api_debug_scenarios__key__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
